
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch17-discovery
  labels:
    component: elasticsearch17
    role: master
spec:
  selector:
    component: elasticsearch17
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP